version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'ci'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    groups:
      timelinx-workspace-dev:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - '*'
      timelinx-workspace-runtime:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - '*'
